# Generated by Django 2.0.7 on 2019-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact', models.CharField(max_length=50, unique=True)),
                ('emergency_contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
