# Generated by Django 2.0.7 on 2019-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='emergency_contact',
            name='emergency_contact',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
