# Generated by Django 2.0.7 on 2019-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passport_stat',
            fields=[
                ('passport_status', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('extra_documents', models.CharField(max_length=30)),
            ],
        ),
    ]
