# Generated by Django 2.0.7 on 2019-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passport_holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.TextField()),
                ('applicant_name', models.TextField()),
                ('fathers_name', models.TextField()),
                ('mothers_name', models.TextField()),
                ('sex', models.TextField()),
                ('place_of_birth', models.TextField()),
                ('citizenship_acquiring_method', models.TextField()),
                ('lost_citizenship', models.DateField()),
                ('citizen_of_another_country_before', models.TextField()),
                ('served_military_of_other_country', models.TextField()),
                ('present_address', models.TextField()),
                ('home_address', models.TextField()),
                ('preferred_delivery_address', models.TextField()),
                ('contact_number', models.TextField()),
                ('email_address', models.TextField()),
                ('spouse_name', models.TextField()),
                ('emergency_contact', models.TextField()),
                ('issuing_authority', models.TextField()),
                ('fathers_citizenship', models.TextField()),
                ('mothers_citizenship', models.TextField()),
                ('passport_status', models.TextField()),
                ('fathers_last_name', models.TextField()),
                ('mothers_last_name', models.TextField()),
                ('place_issued', models.TextField()),
                ('date_issued', models.DateField()),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
