# Generated by Django 2.0.7 on 2019-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_holder',
            name='lost_citizenship',
            field=models.TextField(),
        ),
    ]
