# Generated by Django 2.0.7 on 2019-11-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0003_auto_20191123_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_holder',
            name='lost_citizenship',
            field=models.BooleanField(),
        ),
    ]
