# Generated by Django 2.0.7 on 2019-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0004_auto_20191123_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_holder',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
    ]
