# Generated by Django 2.0.7 on 2019-11-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0005_auto_20191123_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport_holder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='lost_citizenship',
        ),
        migrations.AddField(
            model_name='passport_holder',
            name='lost_citizenship_before',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passport_holder',
            name='emergency_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_contact.emergency_contact', to_field='emergency_contact'),
        ),
        migrations.AlterField(
            model_name='passport_holder',
            name='passport_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
