# Generated by Django 2.0.7 on 2019-11-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0006_auto_20191123_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_holder',
            name='emergency_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_contact.emergency_contact'),
        ),
        migrations.AlterField(
            model_name='passport_holder',
            name='passport_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_stat.passport_stat'),
        ),
    ]
