# Generated by Django 2.0.7 on 2019-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0007_auto_20191123_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_holder',
            name='citizenship_acquiring_method',
            field=models.CharField(choices=[('B', 'By Birth'), ('N', 'By Naturalization'), ('R', 'By Re-acquisition'), ('E', 'By Election'), ('L', 'By Legislation')], max_length=30),
        ),
    ]
