# Generated by Django 2.0.7 on 2019-11-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0008_auto_20191124_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport_holder',
            name='fathers_last_name',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='mothers_last_name',
        ),
    ]
