# Generated by Django 2.0.7 on 2019-11-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport_holder', '0009_auto_20191126_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport_holder',
            name='citizen_of_another_country_before',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='fathers_citizenship',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='lost_citizenship_before',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='mothers_citizenship',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='place_issued',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='served_military_of_other_country',
        ),
        migrations.RemoveField(
            model_name='passport_holder',
            name='spouse_name',
        ),
    ]
